import { TriggerRatings } from './types'
import { fetchTriggerData } from '../api/triggers'

export const MOVIE_TRIGGER_DATA: Record<number, TriggerRatings> = {
  663712: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 2,
    bodyHorror: 1,
    surgery: 0,
    isolation: 1,
    doom: 2,
    possession: 2,
    torture: 1,
    claustrophobia: 1,
  },
  539: {
    doesTheDogDie: 0,
    jumpScare: 1,
    blood: 2,
    bodyHorror: 0,
    surgery: 0,
    isolation: 1,
    doom: 1,
    possession: 0,
    torture: 1,
    claustrophobia: 0,
  },
  694: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 1,
    bodyHorror: 2,
    surgery: 0,
    isolation: 2,
    doom: 2,
    possession: 0,
    torture: 2,
    claustrophobia: 2,
  },
  4944: {
    doesTheDogDie: 0,
    jumpScare: 1,
    blood: 2,
    bodyHorror: 1,
    surgery: 1,
    isolation: 0,
    doom: 1,
    possession: 0,
    torture: 2,
    claustrophobia: 0,
  },
  680: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 2,
    bodyHorror: 2,
    surgery: 0,
    isolation: 1,
    doom: 1,
    possession: 0,
    torture: 1,
    claustrophobia: 1,
  },
  4348: {
    doesTheDogDie: 0,
    jumpScare: 1,
    blood: 1,
    bodyHorror: 0,
    surgery: 0,
    isolation: 1,
    doom: 1,
    possession: 0,
    torture: 0,
    claustrophobia: 0,
  },
  346: {
    doesTheDogDie: 0,
    jumpScare: 0,
    blood: 1,
    bodyHorror: 0,
    surgery: 0,
    isolation: 0,
    doom: 2,
    possession: 0,
    torture: 1,
    claustrophobia: 0,
  },
  1724: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 2,
    bodyHorror: 1,
    surgery: 0,
    isolation: 2,
    doom: 1,
    possession: 0,
    torture: 1,
    claustrophobia: 2,
  },
  745: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 1,
    bodyHorror: 1,
    surgery: 0,
    isolation: 1,
    doom: 1,
    possession: 0,
    torture: 0,
    claustrophobia: 1,
  },
  424: {
    doesTheDogDie: 0,
    jumpScare: 1,
    blood: 2,
    bodyHorror: 2,
    surgery: 0,
    isolation: 1,
    doom: 0,
    possession: 0,
    torture: 2,
    claustrophobia: 0,
  },
  1396: {
    doesTheDogDie: 0,
    jumpScare: 1,
    blood: 2,
    bodyHorror: 0,
    surgery: 0,
    isolation: 0,
    doom: 1,
    possession: 0,
    torture: 0,
    claustrophobia: 0,
  },
  280: {
    doesTheDogDie: 0,
    jumpScare: 0,
    blood: 1,
    bodyHorror: 0,
    surgery: 0,
    isolation: 1,
    doom: 2,
    possession: 0,
    torture: 0,
    claustrophobia: 0,
  },
  1701: {
    doesTheDogDie: 0,
    jumpScare: 1,
    blood: 1,
    bodyHorror: 2,
    surgery: 1,
    isolation: 0,
    doom: 1,
    possession: 0,
    torture: 1,
    claustrophobia: 0,
  },
  10336: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 1,
    bodyHorror: 0,
    surgery: 0,
    isolation: 2,
    doom: 2,
    possession: 0,
    torture: 1,
    claustrophobia: 2,
  },
  246655: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 1,
    bodyHorror: 0,
    surgery: 0,
    isolation: 1,
    doom: 1,
    possession: 0,
    torture: 0,
    claustrophobia: 0,
  },
  346364: {
    doesTheDogDie: 1,
    jumpScare: 2,
    blood: 2,
    bodyHorror: 1,
    surgery: 0,
    isolation: 1,
    doom: 1,
    possession: 0,
    torture: 1,
    claustrophobia: 0,
  },
  10340: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 2,
    bodyHorror: 2,
    surgery: 0,
    isolation: 0,
    doom: 1,
    possession: 0,
    torture: 2,
    claustrophobia: 0,
  },
  807172: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 2,
    bodyHorror: 2,
    surgery: 1,
    isolation: 1,
    doom: 1,
    possession: 0,
    torture: 2,
    claustrophobia: 1,
  },
  11: {
    doesTheDogDie: 0,
    jumpScare: 0,
    blood: 1,
    bodyHorror: 0,
    surgery: 0,
    isolation: 1,
    doom: 1,
    possession: 0,
    torture: 0,
    claustrophobia: 0,
  },
  497: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 2,
    bodyHorror: 1,
    surgery: 0,
    isolation: 0,
    doom: 1,
    possession: 0,
    torture: 1,
    claustrophobia: 0,
  },
  672: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 2,
    bodyHorror: 1,
    surgery: 0,
    isolation: 1,
    doom: 1,
    possession: 0,
    torture: 1,
    claustrophobia: 1,
  },
  637: {
    doesTheDogDie: 0,
    jumpScare: 1,
    blood: 1,
    bodyHorror: 0,
    surgery: 0,
    isolation: 1,
    doom: 1,
    possession: 0,
    torture: 0,
    claustrophobia: 0,
  },
  76493: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 2,
    bodyHorror: 2,
    surgery: 1,
    isolation: 2,
    doom: 2,
    possession: 0,
    torture: 2,
    claustrophobia: 2,
  },
  1091: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 2,
    bodyHorror: 2,
    surgery: 0,
    isolation: 1,
    doom: 1,
    possession: 0,
    torture: 1,
    claustrophobia: 1,
  },
  613504: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 1,
    bodyHorror: 0,
    surgery: 0,
    isolation: 1,
    doom: 1,
    possession: 0,
    torture: 0,
    claustrophobia: 0,
  },
  9741: {
    doesTheDogDie: 0,
    jumpScare: 1,
    blood: 1,
    bodyHorror: 0,
    surgery: 0,
    isolation: 2,
    doom: 2,
    possession: 0,
    torture: 1,
    claustrophobia: 2,
  },
  296: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 2,
    bodyHorror: 1,
    surgery: 0,
    isolation: 1,
    doom: 1,
    possession: 0,
    torture: 1,
    claustrophobia: 0,
  },
  644479: {
    doesTheDogDie: 0,
    jumpScare: 1,
    blood: 1,
    bodyHorror: 0,
    surgery: 0,
    isolation: 0,
    doom: 0,
    possession: 0,
    torture: 0,
    claustrophobia: 0,
  },
  438631: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 2,
    bodyHorror: 1,
    surgery: 0,
    isolation: 1,
    doom: 2,
    possession: 2,
    torture: 1,
    claustrophobia: 1,
  },
  1359: {
    doesTheDogDie: 0,
    jumpScare: 1,
    blood: 2,
    bodyHorror: 0,
    surgery: 0,
    isolation: 0,
    doom: 1,
    possession: 0,
    torture: 1,
    claustrophobia: 0,
  },
  43074: {
    doesTheDogDie: 1,
    jumpScare: 2,
    blood: 2,
    bodyHorror: 2,
    surgery: 0,
    isolation: 1,
    doom: 2,
    possession: 0,
    torture: 2,
    claustrophobia: 1,
  },
  760161: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 2,
    bodyHorror: 1,
    surgery: 0,
    isolation: 1,
    doom: 1,
    possession: 1,
    torture: 1,
    claustrophobia: 1,
  },
  1217: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 1,
    bodyHorror: 0,
    surgery: 0,
    isolation: 0,
    doom: 1,
    possession: 0,
    torture: 0,
    claustrophobia: 0,
  },
  4026: {
    doesTheDogDie: 1,
    jumpScare: 1,
    blood: 2,
    bodyHorror: 2,
    surgery: 0,
    isolation: 1,
    doom: 1,
    possession: 0,
    torture: 2,
    claustrophobia: 1,
  },
  826758: {
    doesTheDogDie: 1,
    jumpScare: 2,
    blood: 2,
    bodyHorror: 1,
    surgery: 0,
    isolation: 2,
    doom: 2,
    possession: 0,
    torture: 1,
    claustrophobia: 2,
  },
  533535: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 2,
    bodyHorror: 1,
    surgery: 0,
    isolation: 1,
    doom: 1,
    possession: 1,
    torture: 1,
    claustrophobia: 1,
  },
  1590: {
    doesTheDogDie: 0,
    jumpScare: 1,
    blood: 1,
    bodyHorror: 0,
    surgery: 0,
    isolation: 1,
    doom: 1,
    possession: 0,
    torture: 0,
    claustrophobia: 0,
  },
  758323: {
    doesTheDogDie: 0,
    jumpScare: 1,
    blood: 2,
    bodyHorror: 1,
    surgery: 0,
    isolation: 0,
    doom: 1,
    possession: 0,
    torture: 1,
    claustrophobia: 0,
  },
  635302: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 2,
    bodyHorror: 0,
    surgery: 0,
    isolation: 1,
    doom: 2,
    possession: 2,
    torture: 1,
    claustrophobia: 1,
  },
  646385: {
    doesTheDogDie: 0,
    jumpScare: 2,
    blood: 1,
    bodyHorror: 1,
    surgery: 0,
    isolation: 1,
    doom: 2,
    possession: 2,
    torture: 0,
    claustrophobia: 1,
  },
  487558: {
    doesTheDogDie: 0,
    jumpScare: 1,
    blood: 1,
    bodyHorror: 0,
    surgery: 0,
    isolation: 0,
    doom: 1,
    possession: 0,
    torture: 0,
    claustrophobia: 0,
  },
}

export function getTriggerDataForMovie(movieId: number): TriggerRatings {
  return MOVIE_TRIGGER_DATA[movieId] || {
    doesTheDogDie: null,
    jumpScare: null,
    blood: null,
    bodyHorror: null,
    surgery: null,
    isolation: null,
    doom: null,
    possession: null,
    torture: null,
    claustrophobia: null,
  }
}

export async function getTriggerDataForMovieAsync(movieId: number): Promise<TriggerRatings> {
  const apiData = await fetchTriggerData(movieId)
  
  if (apiData) {
    return apiData
  }
  
  return getTriggerDataForMovie(movieId)
}

export function generateRandomTriggerData(): TriggerRatings {
  const randomIntensity = () => {
    const rand = Math.random()
    if (rand < 0.3) return 0
    if (rand < 0.6) return 1
    return 2
  }

  return {
    doesTheDogDie: Math.random() < 0.15 ? randomIntensity() : 0,
    jumpScare: randomIntensity(),
    blood: randomIntensity(),
    bodyHorror: randomIntensity(),
    surgery: Math.random() < 0.3 ? randomIntensity() : 0,
    isolation: randomIntensity(),
    doom: randomIntensity(),
    possession: Math.random() < 0.4 ? randomIntensity() : 0,
    torture: Math.random() < 0.5 ? randomIntensity() : 0,
    claustrophobia: Math.random() < 0.4 ? randomIntensity() : 0,
  }
}
