import { LanguageCodes } from "./interface";

// Default:10, Limit:40
export const RESULT_COUNT = 20;

export const LANGUAGES: LanguageCodes = [
  { country: "Abkhazian", abreviation: "ab" },
  { country: "Afar", abreviation: "aa" },
  { country: "Afrikaans", abreviation: "af" },
  { country: "Akan", abreviation: "ak" },
  { country: "Albanian", abreviation: "sq" },
  { country: "Amharic", abreviation: "am" },
  { country: "Arabic", abreviation: "ar" },
  { country: "Aragonese", abreviation: "an" },
  { country: "Armenian", abreviation: "hy" },
  { country: "Assamese", abreviation: "as" },
  { country: "Avaric", abreviation: "av" },
  { country: "Avestan", abreviation: "ae" },
  { country: "Aymara", abreviation: "ay" },
  { country: "Azerbaijani", abreviation: "az" },
  { country: "Bambara", abreviation: "bm" },
  { country: "Bashkir", abreviation: "ba" },
  { country: "Basque", abreviation: "eu" },
  { country: "Belarusian", abreviation: "be" },
  { country: "Bengali", abreviation: "bn" },
  { country: "Bislama", abreviation: "bi" },
  { country: "Bosnian", abreviation: "bs" },
  { country: "Breton", abreviation: "br" },
  { country: "Bulgarian", abreviation: "bg" },
  { country: "Burmese", abreviation: "my" },
  { country: "Catalan, Valencian", abreviation: "ca" },
  { country: "Chamorro", abreviation: "ch" },
  { country: "Chechen", abreviation: "ce" },
  { country: "Chichewa, Chewa, Nyanja", abreviation: "ny" },
  { country: "Chinese", abreviation: "zh" },
  { country: "Slavonic", abreviation: "cu" },
  { country: "Chuvash", abreviation: "cv" },
  { country: "Cornish", abreviation: "kw" },
  { country: "Corsican", abreviation: "co" },
  { country: "Cree", abreviation: "cr" },
  { country: "Croatian", abreviation: "hr" },
  { country: "Czech", abreviation: "cs" },
  { country: "Danish", abreviation: "da" },
  { country: "Divehi, Dhivehi, Maldivian", abreviation: "dv" },
  { country: "Dutch, Flemish", abreviation: "nl" },
  { country: "Dzongkha", abreviation: "dz" },
  { country: "English", abreviation: "en" },
  { country: "Esperanto", abreviation: "eo" },
  { country: "Estonian", abreviation: "et" },
  { country: "Ewe", abreviation: "ee" },
  { country: "Faroese", abreviation: "fo" },
  { country: "Fijian", abreviation: "fj" },
  { country: "Finnish", abreviation: "fi" },
  { country: "French", abreviation: "fr" },
  { country: "Western Frisian", abreviation: "fy" },
  { country: "Fulah", abreviation: "ff" },
  { country: "Gaelic, Scottish Gaelic", abreviation: "gd" },
  { country: "Galician", abreviation: "gl" },
  { country: "Ganda", abreviation: "lg" },
  { country: "Georgian", abreviation: "ka" },
  { country: "German", abreviation: "de" },
  { country: "Greek", abreviation: "el" },
  { country: "Kalaallisut, Greenlandic", abreviation: "kl" },
  { country: "Guarani", abreviation: "gn" },
  { country: "Gujarati", abreviation: "gu" },
  { country: "Haitian, Haitian Creole", abreviation: "ht" },
  { country: "Hausa", abreviation: "ha" },
  { country: "Hebrew", abreviation: "he" },
  { country: "Herero", abreviation: "hz" },
  { country: "Hindi", abreviation: "hi" },
  { country: "Hiri Motu", abreviation: "ho" },
  { country: "Hungarian", abreviation: "hu" },
  { country: "Icelandic", abreviation: "is" },
  { country: "Ido", abreviation: "io" },
  { country: "Igbo", abreviation: "ig" },
  { country: "Indonesian", abreviation: "id" },
  { country: "Interlingua", abreviation: "ia" },
  { country: "Interlingue, Occidental", abreviation: "ie" },
  { country: "Inuktitut", abreviation: "iu" },
  { country: "Inupiaq", abreviation: "ik" },
  { country: "Irish", abreviation: "ga" },
  { country: "Italian", abreviation: "it" },
  { country: "Japanese", abreviation: "ja" },
  { country: "Javanese", abreviation: "jv" },
  { country: "Kannada", abreviation: "kn" },
  { country: "Kanuri", abreviation: "kr" },
  { country: "Kashmiri", abreviation: "ks" },
  { country: "Kazakh", abreviation: "kk" },
  { country: "Central Khmer", abreviation: "km" },
  { country: "Kikuyu, Gikuyu", abreviation: "ki" },
  { country: "Kinyarwanda", abreviation: "rw" },
  { country: "Kirghiz, Kyrgyz", abreviation: "ky" },
  { country: "Komi", abreviation: "kv" },
  { country: "Kongo", abreviation: "kg" },
  { country: "Korean", abreviation: "ko" },
  { country: "Kuanyama, Kwanyama", abreviation: "kj" },
  { country: "Kurdish", abreviation: "ku" },
  { country: "Lao", abreviation: "lo" },
  { country: "Latin", abreviation: "la" },
  { country: "Latvian", abreviation: "lv" },
  { country: "Limburgan, Limburger, Limburgish", abreviation: "li" },
  { country: "Lingala", abreviation: "ln" },
  { country: "Lithuanian", abreviation: "lt" },
  { country: "Luba-Katanga", abreviation: "lu" },
  { country: "Luxembourgish, Letzeburgesch", abreviation: "lb" },
  { country: "Macedonian", abreviation: "mk" },
  { country: "Malagasy", abreviation: "mg" },
  { country: "Malay", abreviation: "ms" },
  { country: "Malayalam", abreviation: "ml" },
  { country: "Maltese", abreviation: "mt" },
  { country: "Manx", abreviation: "gv" },
  { country: "Maori", abreviation: "mi" },
  { country: "Marathi", abreviation: "mr" },
  { country: "Marshallese", abreviation: "mh" },
  { country: "Mongolian", abreviation: "mn" },
  { country: "Nauru", abreviation: "na" },
  { country: "Navajo, Navaho", abreviation: "nv" },
  { country: "North Ndebele", abreviation: "nd" },
  { country: "South Ndebele", abreviation: "nr" },
  { country: "Ndonga", abreviation: "ng" },
  { country: "Nepali", abreviation: "ne" },
  { country: "Norwegian", abreviation: "no" },
  { country: "Norwegian Bokmål", abreviation: "nb" },
  { country: "Norwegian Nynorsk", abreviation: "nn" },
  { country: "Sichuan Yi, Nuosu", abreviation: "ii" },
  { country: "Occitan", abreviation: "oc" },
  { country: "Ojibwa", abreviation: "oj" },
  { country: "Oriya", abreviation: "or" },
  { country: "Oromo", abreviation: "om" },
  { country: "Ossetian, Ossetic", abreviation: "os" },
  { country: "Pali", abreviation: "pi" },
  { country: "Pashto, Pushto", abreviation: "ps" },
  { country: "Persian", abreviation: "fa" },
  { country: "Polish", abreviation: "pl" },
  { country: "Portuguese", abreviation: "pt" },
  { country: "Punjabi, Panjabi", abreviation: "pa" },
  { country: "Quechua", abreviation: "qu" },
  { country: "Romanian, Moldavian, Moldovan", abreviation: "ro" },
  { country: "Romansh", abreviation: "rm" },
  { country: "Rundi", abreviation: "rn" },
  { country: "Russian", abreviation: "ru" },
  { country: "Northern Sami", abreviation: "se" },
  { country: "Samoan", abreviation: "sm" },
  { country: "Sango", abreviation: "sg" },
  { country: "Sanskrit", abreviation: "sa" },
  { country: "Sardinian", abreviation: "sc" },
  { country: "Serbian", abreviation: "sr" },
  { country: "Shona", abreviation: "sn" },
  { country: "Sindhi", abreviation: "sd" },
  { country: "Sinhala, Sinhalese", abreviation: "si" },
  { country: "Slovak", abreviation: "sk" },
  { country: "Slovenian", abreviation: "sl" },
  { country: "Somali", abreviation: "so" },
  { country: "Southern Sotho", abreviation: "st" },
  { country: "Spanish, Castilian", abreviation: "es" },
  { country: "Sundanese", abreviation: "su" },
  { country: "Swahili", abreviation: "sw" },
  { country: "Swati", abreviation: "ss" },
  { country: "Swedish", abreviation: "sv" },
  { country: "Tagalog", abreviation: "tl" },
  { country: "Tahitian", abreviation: "ty" },
  { country: "Tajik", abreviation: "tg" },
  { country: "Tamil", abreviation: "ta" },
  { country: "Tatar", abreviation: "tt" },
  { country: "Telugu", abreviation: "te" },
  { country: "Thai", abreviation: "th" },
  { country: "Tibetan", abreviation: "bo" },
  { country: "Tigrinya", abreviation: "ti" },
  { country: "Tonga (Tonga Islands)", abreviation: "to" },
  { country: "Tsonga", abreviation: "ts" },
  { country: "Tswana", abreviation: "tn" },
  { country: "Turkish", abreviation: "tr" },
  { country: "Turkmen", abreviation: "tk" },
  { country: "Twi", abreviation: "tw" },
  { country: "Uighur, Uyghur", abreviation: "ug" },
  { country: "Ukrainian", abreviation: "uk" },
  { country: "Urdu", abreviation: "ur" },
  { country: "Uzbek", abreviation: "uz" },
  { country: "Venda", abreviation: "ve" },
  { country: "Vietnamese", abreviation: "vi" },
  { country: "Volapük", abreviation: "vo" },
  { country: "Walloon", abreviation: "wa" },
  { country: "Welsh", abreviation: "cy" },
  { country: "Wolof", abreviation: "wo" },
  { country: "Xhosa", abreviation: "xh" },
  { country: "Yiddish", abreviation: "yi" },
  { country: "Yoruba", abreviation: "yo" },
  { country: "Zhuang,Chuang", abreviation: "za" },
  { country: "Zulu", abreviation: "zu" },
];
